[package]
name = "dec001-openmls-measurement"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
ed25519-dalek = "=2.2.0"
hex = "=0.4.3"
openmls = { path = "openmls-src/openmls", default-features = false, features = ["libcrux-provider", "test-utils"] }
openmls_basic_credential = { path = "openmls-src/basic_credential" }
openmls_libcrux_crypto = { path = "openmls-src/libcrux_crypto" }
serde_json = "=1.0.151"
sha2 = "=0.10.9"
tls_codec = { version = "=0.4.2", features = ["derive", "serde", "mls"] }
